FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

# Install NPM
RUN apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
  && apt-get install -y nodejs \
  && curl -L https://www.npmjs.com/install.sh | sh

# Install Yarn
RUN npm install -g yarn

RUN mkdir /frontend 
# the "backend" dir must be mounted as /app and
# the "frontend" dir must be mounted as /frontend in the run command

# 
EXPOSE 3000

# Install Python Dependencies
COPY ./backend/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# python venv is activated in here
COPY docker/docker-dev-start.sh /

CMD ["./docker-dev-start.sh"]

