"""empty message

Revision ID: d4850c215d1f
Revises: e7b953a34804
Create Date: 2020-07-16 12:56:31.790134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4850c215d1f'
down_revision = 'e7b953a34804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
